# Generated by Django 4.2.20 on 2025-04-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presence", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[("employe", "Employé"), ("manager", "Manager"), ("rh", "RH")],
                default="employe",
                max_length=20,
            ),
        ),
    ]
