# Generated by Django 4.2.20 on 2025-05-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presence", "0003_presence"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="last_logout",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
