# Generated by Django 4.2.20 on 2025-05-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presence", "0004_employee_last_logout"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="absencereport",
            options={"ordering": ["-date", "-start_time"]},
        ),
        migrations.AddField(
            model_name="absencereport",
            name="status",
            field=models.CharField(
                choices=[("absent", "Absent"), ("present", "Present")],
                default="absent",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="absencereport",
            name="reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
