# Generated by Django 4.2.20 on 2025-05-21 12:08

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0006_notification'),  # Dernière migration existante
    ]

    operations = [
        migrations.AddField(
            model_name='absencereport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='absencereport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
