# Generated by Django 4.2.20 on 2025-05-21 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("presence", "0011_absencereport_justification_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["-sent_at"],
                "permissions": [
                    ("can_send_message", "Peut envoyer des messages"),
                    ("can_view_all_messages", "Peut voir tous les messages"),
                ],
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.AddField(
            model_name="message",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Indique si le message a été archivé",
                verbose_name="Archivé",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Message auquel il est répondu",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="presence.message",
                verbose_name="Message parent",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Lu le"),
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(
                help_text="Contenu du message", verbose_name="Message"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="read",
            field=models.BooleanField(
                default=False,
                help_text="Indique si le message a été lu par le destinataire",
                verbose_name="Lu",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Destinataire",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Expéditeur",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Envoyé le"),
        ),
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(
                help_text="Objet du message (200 caractères max)",
                max_length=200,
                verbose_name="Objet",
            ),
        ),
    ]
