# Generated by Django 4.2.20 on 2025-05-21 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("presence", "0012_alter_message_options_message_is_archived_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_archived",
        ),
        migrations.RemoveField(
            model_name="message",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="message",
            name="read_at",
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="message",
            name="read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(max_length=200),
        ),
    ]
